#!/usr/bin/env python

import sys

from pynput.mouse import Controller
import time


def move_mouse(script_end, sleep_interval, mouse, y):
    if script_end > time.time():
        mouse.move(0, y)
        time.sleep(sleep_interval)
        move_mouse(script_end, sleep_interval, mouse, -y)


if __name__ == '__main__':
    if len(sys.argv) < 2:
        raise Exception("Provide script timeout")

    try:
        script_timeout = int(sys.argv[1])
    except ValueError:
        raise Exception("Provide script timout as integer")

    script_end = time.time() + script_timeout * 60
    mouse = Controller()
    move_mouse(script_end=script_end, sleep_interval=60, mouse=mouse, y=1)
